;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "zprint-skill")
(def path ".")
(def version "0.1.8")
(def tag "0.1.8")
(def generated-at "2020-07-29T18:37:43Z")
