;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "zprint-skill")
(def path ".")
(def version "0.1.1")
(def tag "0.1.1")
(def generated-at "2020-07-06T22:43:42Z")
